### ISSUE TITLE
Add modules to the pkg command

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#102]
Add the ability to define an external "module" that can be imported into a template with a new directive, `!Rain::Module`. Allow these modules to inherit from existing types.

Exploring the idea in PR #101 

## FAQ
- **What's the difference between this and `!Rain::Include` ?**
    The `Include` directive simply pastes in the contents of referenced file. A `Module` inherits from an existing type, allowing defaults to be provided by the module and then overridden by the consumer.

- **What's the difference between this and a CloudFormation registry module?**
    A registry module is installed server-side and processed by the CloudFormation back end. They are essentially template snippets, which do not allow for type inheritance. A rain module is client-side, resulting in a rendered template which is then deployed to CloudFormation. A CloudFormation registry module can be installed into an account/region, so that it looks and feels like any other resource type.

## Sample
Below is a sample module that defines a compliant bucket that can pass `cfn_nag` checks by default. It also allows the user to define any of the additional `AWS::S3::Bucket` properties, and to override the defaults set within the module.

```yaml
Description: |
  This module creates a bucket that will pass cfn_nag checks by 
  configuring common best practices like encryption and logging.
  This is a rain module, which allows for existing resources to 
  be extended, similar to a sub-class in an object oriented language.

# New properties that the user can set
Parameters:

  LogBucketName:
    Type: String
    Description: The name of the log bucket

# Additional resources to be added to the template

Resources:

  # This is a reserved name that means this is the extended resource
  ModuleExtension:

    Metadata:
      # This is required to tell rain what resource we are extending
      Extends: AWS::S3::Bucket
      Comment: A bucket that will pass cfn_nag checks
      cfn_nag:
        rules_to_suppress:
          - id: W51
            reason: "Will be added by the consumer"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

    # Inherits all properties of a regular bucket
    # The user can override any of these defaults in the template that uses this module
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
             SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: test-tag
          Value: test-value1
  
  # Any other resources we define will be added to the template
  # The logical name will be the user-defined resource name plus this name, 
  # for example "ModuleExample-LogBucket"
  LogBucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: This bucket records access logs for MyBucket
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "This is the log bucket"
          - id: W51
            reason: "Will be added by the consumer"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref LogBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```

This is how the module would be consumed:

```yaml
Resources:

  ModuleExample:

    Type: !Rain::Module "file://../../modules/bucket.yaml"

    Properties:

      # This is a new property added by the module
      LogBucketName: test-module-log-bucket

      # This is a regular property that the module doesn't set
      BucketName: test-module-bucket

      # This is a property set by the module that we will override
      Tags:
        - Key: test-tag
          Value: test-value2
```

After running `rain pkg`, this would be the resulting template:

```yaml
Resources:

  ModuleExample:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: A bucket that will pass cfn_nag checks
      cfn_nag:
        rules_to_suppress:
          - id: W51
            reason: "Will be added by the consumer"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: test-module-bucket
      LoggingConfiguration:
        DestinationBucketName: !Ref ModuleExample-LogBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
             SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: test-tag
          Value: test-value2

LogBucket:
    Type: AWS::S3::Bucket
    Metadata:
      Comment: This bucket records access logs for MyBucket
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "This is the log bucket"
          - id: W51
            reason: "Will be added by the consumer"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: test-module-log-bucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
```
