### ISSUE TITLE
Allow formatting with long-format version of intrinsic functions

### ISSUE THREAD

**Issue by dinakar29** [aws-cloudformation/rain#12]
Hi!

First of all - this project, along with [aws-cloudformation-template-formatter](https://github.com/awslabs/aws-cloudformation-template-formatter), is an awesome tool for formatting YAML-formatted CloudFormation templates. So thank you for creating this, as it is a huge time saver.

Second - is it possible to add the ability to format the CloudFormation templates with the long-format version of intrinsic functions?

For instance, suppose there's a template that looks like this:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Defines a certificate for DomainName and a SAN of *.DomainName
Parameters:
  DomainName: {Type: String}
  ValidationDomain: {Type: String}
Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: {Ref: DomainName}
      DomainValidationOptions:
      - DomainName: {Ref: DomainName}
        ValidationDomain:  {Ref: ValidationDomain}
      - DomainName:
          Fn::Join: ['.', ['*', {Ref: DomainName}]]
        ValidationDomain:  {Ref: ValidationDomain}
      SubjectAlternativeNames:
        - Fn::Join: ['.', ['*',{Ref: DomainName}]]

Outputs:
  CertificateArn:
    Description: ARN of certificate
    Value: {Ref: Certificate}
```

`rain fmt -c <template>` results in a template that looks like this:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Defines a certificate for DomainName and a SAN of *.DomainName
Parameters:
  DomainName:
    Type: String
  ValidationDomain:
    Type: String
Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          ValidationDomain: !Ref ValidationDomain
        - DomainName: !Join
            - .
            - - "*"
              - Ref: DomainName
          ValidationDomain: !Ref ValidationDomain
      SubjectAlternativeNames:
        - "Fn::Join":
            - .
            - - "*"
              - Ref: DomainName
Outputs:
  CertificateArn:
    Description: ARN of certificate
    Value: !Ref Certificate
```

Would it be possible to add an additional option to `rain fmt` so that the long-format (`Ref:` instead of `!Ref` | `Fn::Join` instead of ` !Join` etc) of the [intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) is retained?
