### ISSUE TITLE
fmt command gives "semantic difference after formatting" error for multi-line values

### ISSUE THREAD

**Issue by JWFGit** [aws-cloudformation/rain#126]
rain fmt command does not work with multi-line yaml

Using this CF template
```
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Template generated by rain
  and edited my me
Resources:
  MyFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import cfnresponse

          def handler(event, context):
              print(event)

      Description: Test lambda for rain fmt
      FunctionName: my-lambda
      Handler: index.handler
      ReservedConcurrentExecutions: 0 # Optional
      Role: arn:aws:iam::123456789012:role/aws-service-role/support.amazonaws.com/AWSServiceRoleForSupport
      Runtime: python3.8

      Tags:
        - Key: my_tag
          Value: ME
      Timeout: 100

```
running ./rain --version

> Rain v1.3.3 darwin/amd64

when the fmt command is run
> ./rain fmt -v my_test/lambda.yaml
```
semantic difference after formatting:
(>) Description: |
  Template generated by rain

  and edited my me
(|) Resources:
(|)   MyFunction:
(|)     Properties:
(|)       Code:
(>)         ZipFile: |
  i        mport boto3
  i        mport cfnresponse
  d        ef handler(event, context):
              print(event)

```
