### ISSUE TITLE
It should not touch ZipFile lambdas

### ISSUE THREAD

**Issue by filipeandre** [aws-cloudformation/rain#132]
I tryed it with my CDK generated yaml.

It formated my lambda ZipFile body, and it shoudn't.

Before:

```
   ArtifactsDeployment4DBAE441:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "import random\nimport string\nfrom urllib import request\n\nimport\
          \ boto3\nimport json\n\n\ndef handler(event, context):\n    bucket_name\
```

After:

```
    ArtifactsDeployment4DBAE441:
    Type: AWS::Lambda::Function
    DependsOn:
      - ArtifactsDeploymentLogGroup00A89018
      - ArtifactsDeploymentRoleDefaultPolicyF49E31E5
      - ArtifactsDeploymentRole730D869C
    Properties:
      Code:
        ZipFile: |
          import random
          import string
          from urllib import request

          import boto3
          import json


          def handler(event, context):
              bucket_name = event['ResourceProperties']['BucketName']
```

Can we make the ZipFile content not changed, since it's not yaml?
