### ISSUE TITLE
Shebang Causing Semantic Difference After Formatting Error

### ISSUE THREAD

**Issue by null93** [aws-cloudformation/rain#135]
Hey! First off, I would like to say that I am a big fan _rain_! I recently encountered a weird bug when upgrading from _rain@1.2.0_ to _rain@1.3.3_.

If I have the following file `works.yml`:

```yaml
Resources:
  Works:
    Properties:
      UserData: !Base64
        Fn::Sub:
          - |
            echo foo=${foo}
          - foo: bar
```

When I run `rain fmt works.yml`, everything works just fine. But when I add a shebang to it, and the file `does-not-work.yml` looks like this:

```yaml
Resources:
  DoesNotWork:
    Properties:
      UserData: !Base64
        Fn::Sub:
          - |
            #!/bin/bash -xe
            echo foo=${foo}
          - foo: bar
```

Running `rain fmt does-not-work.yml` gives the following error:

```
semantic difference after formatting:
(|) Resources:
(|)   Works:
(|)     Properties:
(|)       UserData:
(|)         Fn::Base64:
(|)           Fn::Sub:
(>)             [0]: |2
  #            !/bin/bash -xe
  e            cho foo=${foo}
```

The only way to fix this is to add a new line after the pipe like so:

```yaml
Resources:
  Fix:
    Properties:
      UserData: !Base64
        Fn::Sub:
          - |

            #!/bin/bash -xe
            echo foo=${foo}
          - foo: bar
```

Obviously the shebang is required. From AWS [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html#user-data-shell-scripts):

> User data shell scripts must start with the #! characters and the path to the interpreter you want to read the script (commonly /bin/bash)

This could be related to #103.

Some additional information:

- MacOS M2 (arm64v8)
- Installed via brew
