### ISSUE TITLE
How to use tags

### ISSUE THREAD

**Issue by a-mymt** [aws-cloudformation/rain#139]
**Question**
Are tags value attached to all resources in the stack?
`rain deploy xxx.yml stack-name --tags key1=value1,key2=value2`

Are `key1=value1` `key2=value2` tags attached to _igw_,_MyVPCGatewayAttachment_,_vpc1_,_PublicSubnet1_ ?
ex)
```
AWSTemplateFormatVersion: "2010-09-09"

Description: Network Template.

Parameters:
  Env:
    Type: String

  vpcCidr:
    Type: String

Resources:
  igw:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${Env}-igw

  MyVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref igw
      VpcId: !Ref vpc1

  vpc1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref vpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${Env}-vpc1

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: AWS::Region
      CidrBlock: !Select [0, !Cidr [!GetAtt vpc1.CidrBlock, 2, 8]]
      VpcId: !Ref vpc1
      Tags:
        - Key: Name
          Value: !Sub ${Env}-public-subnet-1

Outputs:
  vpc1:
    Value: !Ref vpc1
```
