### ISSUE TITLE
Not reading parameter defaults when `-f` enabled

### ISSUE THREAD

**Issue by ding44** [aws-cloudformation/rain#14]
I've been loving Rain so far. It's removed a lot of the tediousness involved in deploying a CloudFormation template and made our team more productive.

Ran into this issue today when trying to deploy a template with default parameter values. It looks like the command isn't reading the defaults when the `-f` flag is enabled. If you remove the `-f` flag, the default values show up in the parameter input prompts.

To reproduce:

Amazon Linux release 2 (Karoo)
Rain v0.7.2 linux/amd64

Template:
```yaml
#template.yaml

AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  triggerStepFunctionRole:
    Description: IAM role for the triggerStepFunction Lambda function
    Type: String
    Default: arn:aws:iam::XXXXXXXXX:role/triggerStepFunctionRole
  LambdaXrayExecutionRole:
    Description: Role to post to X-Ray
    Type: String
    Default: arn:aws:iam::XXXXXXXXXXX:role/LambdaXrayExecution
...
...
```

Command:
```bash
rain deploy template.yaml STACK-NAME -f --debug
```
Output:
```text
DEBUG: Loaded credentials from default config
Deploying 'template.yaml' as 'tagging-compliance-reports' in us-east-1:
Preparing template... DEBUG: Artifact bucket: rain-artifacts-XXXXXXXXX-us-east-1
DEBUG: Package output: 
Successfully packaged artifacts and wrote output template to file /tmp/006783156.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /tmp/006783156 --stack-name <YOUR STACK NAME>

Checking current status of stack 'tagging-compliance-reports'... DEBUG: Removing temporary template file: /tmp/006783156
Some parameters require values. Set defaults or deploy without the --force flag.
```
