### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by jsutton** [aws-cloudformation/rain#152]
When adding outputs to a deployed nested stack when none were previously defined, the following error is returned:
runtime error: index out of range [1] with length 1

$ rain --version
Rain v1.4.1 linux/amd64

**Comment by ugwis** [comment]
@jsutton Could you provide a minimal reproducible template? Or identify the code from the result of adding --debug option.

**Comment by jsutton** [comment]
This is the final template. The initial template just omits the Outputs section. Removing the stack and redeploying with the Outputs section does result in the same error.
```
Parameters:
  VpcId:
    Type: String
  CidrBlock:
    Description: CIDR Block for the subnet
    Type: String
  AvailabilityZone:
    Description: AZ for the subnet
    Type: String
  MapPublic:
    Description: Map public IP
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
  Name:
    Description: Subnet name
    Type: String
  RouteTableID:
    Description: Subnet route table
    Type: String

Resources:
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VpcId
      CidrBlock: !Ref CidrBlock
      AvailabilityZone: !Ref AvailabilityZone
      MapPublicIpOnLaunch: !Ref MapPublic
      Tags:
        -
          Key: 'Name'
          Value: !Sub '${Name}'

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableID
      SubnetId: !Ref Subnet

Outputs:
  SubnetID:
    Description: Subnet ID
    Value: !Ref Subnet
 ```
