### ISSUE TITLE
Add constants as a !Rain directive

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#156]
Similar to Terraform locals.

```yaml
!Rain::Constants:
    Hello: World
    Nested:
        A: B
        B: C
        
Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Rain::Constant Hello

            or

            BucketName: $Hello
```

How would that work in a `!Sub`? 

`!Sub abc-def-!Rain::Constant Hello` is awkward.

`!Sub abc-def-$Hello` is better

Would this conflict with Ref resolution?
