### ISSUE TITLE
rain fmt doesn't do round trip

### ISSUE THREAD

**Issue by iainelder** [aws-cloudformation/rain#170]
rain fmt doesn't do a round trip with the `--unsorted` option.

Sample template:

```yaml
Parameters:
  RootId:
    Type: String

Resources:

  Sandbox:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      ParentId: !Ref RootId
      Name: Sandbox
```

Command for round trip without `--unsorted`:

```bash
cat template.yaml | rain fmt --json | rain fmt
```

Result looks like YAML again (the keys remain unsorted in this case! Is that deliberate?).

```yaml
Parameters:
  RootId:
    Type: String

Resources:
  Sandbox:
    Type: AWS::Organizations::OrganizationalUnit
    Properties: {ParentId: !Ref "RootId", Name: Sandbox}
```

Command for round trip with `--unsorted`:

```bash
cat template.yaml | rain fmt --json --unsorted | rain fmt --unsorted
```

The result is technically YAML, but I was expecting it to be written on multiple lines!

```yaml
{Parameters: {RootId: {Type: String}}, Resources: {Sandbox: {Type: 'AWS::Organizations::OrganizationalUnit', Properties: {ParentId: !Ref "RootId", Name: Sandbox}}}}
```
