### ISSUE TITLE
Modules can't contain directives

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#180]
```
unable to package template '/Users/ezbeard/Desktop/lambda-template.yaml': yaml: unmarshal errors:
line 0: cannot unmarshal !!map into string
```

```yaml
Description: A module for lambda

Parameters:
  SourceDir:
    Type: String

Resources:
  ModuleExtension:
    Metadata: 
      Extends: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      ReservedConcurrentExecutions: 100
      Code: !Rain::S3 
        Path: !Ref SourceDir 
        Zip: true
        BucketProperty: S3Bucket
        KeyProperty: S3Key

```
