### ISSUE TITLE
rain fmt outputting unicode codes for certain characters

### ISSUE THREAD

**Issue by marionette609** [aws-cloudformation/rain#208]
I'm not seeing this when using rain fmt to convert from json -> yaml, but when converting from yaml -> json it's replacing brackets (< and >) with unicode codes, the use case for this is using SSM parameters as template parameters with specified types.

For example:

```
Parameters:
  pBotToken:
    Type: "AWS::SSM::Parameter::Value<String>"
    Description: Bot Token
    Default: '/token/bot'
    NoEcho: 'true'
```

when converted to json is ending up as 

```
    "Parameters": {
        "pBotToken": {
            "Description": "Bot Token",
            "Type": "AWS::SSM::Parameter::Value\u003cString\u003e",
            "Default": "/token/bot",
            "NoEcho": "true"
        }
    }
```

I'm on Windows 11 using the latest release v1.6.0
