### ISSUE TITLE
The format command does not support yaml anchors when converting to json

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#257]
YAML anchors are supported by Go, but when trying to convert to JSON with `rain fmt -j`, we get an error:

`yaml: unknown anchor 'fooval' referenced`

```yaml
Resources:
  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: &code
        ZipFile: "print(\"Hello World!\")\n"
      FunctionName: my-lambda
      Handler: index.lambda_handler
      Role: !ImportValue 'MyLambdaRoleArn'
      Runtime: python3.8
      Tags:
        - Key: foo
          Value: &fooval myval
        - Key: bar
          Value: *fooval
    Metadata:
      Comment: *code
 ```
