### ISSUE TITLE
Account numbers converted to scientific notation.

### ISSUE THREAD

**Issue by RDittmar** [aws-cloudformation/rain#27]
If a parameter has a string type but is a long number like an account number, when deploying the template the default value is converted to scientific notation.  If the value is re-entered correctly, it is passed in correctly.

`Enter a value for parameter 'Account' (default value: 1.2345678901e+10):`
instead of 
`Enter a value for parameter 'Account' (default value: 012345678901):`

Example template attached.
[sample.txt](https://github.com/aws-cloudformation/rain/files/4885692/sample.txt)

**Comment by stilvoid** [comment]
I'm looking into this one. It looks like it's due to the underlying YAML library correctly misinterpreting the account number value as a number. Before spec v1.2, YAML support octal numbers prefixed with a `0` so there are several conflicting interpretations out there.

**Comment by stilvoid** [comment]
Ok, I've fixed the relevant bug in rain in #28 however there is a underlying problem present in the AWS CLI which is used by rain to perform the packaging step during deployment.

Taking your example template:

`aws cloudformation package --template-file sample.txt --output-template packaged.template --s3-bucket <mybucket>`

I see the following in `packaged.template`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Account:
    Default: 12345678901
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: bucket-${Account}
```

This means that I see a better yet still incorrect value during `rain deploy`:

```
Enter a value for parameter 'Account' (default value: 12345678901):
```

This is not something I can fix in rain (although I will pass the feedback to the AWS CLI team). I would recommend quoting account numbers that start with a zero to avoid the issue :(
