### ISSUE TITLE
Format bug with Fn::GetAZs empty string

### ISSUE THREAD

**Issue by ericzbeard** [aws-cloudformation/rain#273]
```yaml
  PrivateSubnet1Subnet:
    Type: AWS::EC2::Subnet
    Properties:
    AvailabilityZone: !Select [0, Fn::GetAZs: ""]
    CidrBlock: 10.0.128.0/18
    MapPublicIpOnLaunch: false
    VpcId: !Ref VPC
```

The empty string (which means the same as AWS::Region) is converted to null

```
(|) Resources:
(|)   PrivateSubnet1Subnet:
(|)     Properties:
(|)       AvailabilityZone:
(|)         Fn::Select:
(|)           [1]:
(>)             Fn::GetAZs: null
```
