### ISSUE TITLE
erroneous "Should be a number" expects every yaml number to be float64

### ISSUE THREAD

**Issue by mdaniel** [aws-cloudformation/rain#29]
Given:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LG:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
```
When
```console
$ ./rain-v0.9.0_linux-amd64/rain check float_bug.yaml 
```
Then:
```
float_bug.yaml: not ok
  Resources:                                                                                                                                               
    LG:
      Properties:
        RetentionInDays: Should be a number
```
due to:
```go
   _, ok := prop.Value().(float64)
```
instead of `_, ok := prop.Value().(int)`
