### ISSUE TITLE
BUG: Updating from 1.7.5 to 1.8.1 causes `Properties validation failed for resource Schedule with message: [#/FlexibleTimeWindow/Mode: false is not a valid enum value]`

### ISSUE THREAD

**Issue by r-heimann** [aws-cloudformation/rain#319]
Hi,

updated `rain` from v1.7.5 to v1.8.1, it now causes

```
Properties validation failed for resource Schedule with message:
[#/FlexibleTimeWindow/Mode: false is not a valid enum value]
```

Affected CloudFormation Resource: `AWS::Scheduler::Schedule`
Example:

```yaml
  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      GroupName: !Ref ScheduleGroupName
      ScheduleExpression: "rate(5 minutes)"
      ScheduleExpressionTimezone: "Europe/Berlin"
      FlexibleTimeWindow:
        Mode: "OFF"
      State: "ENABLED"
      Target:
        Arn: !GetAtt LambdaFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn
```

rain 1.8.1 artifact:

```yaml
  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      FlexibleTimeWindow:
        Mode: OFF # <- This seems to be affected
      GroupName: !Ref ScheduleGroupName
      ScheduleExpression: rate(5 minutes)
      ScheduleExpressionTimezone: Europe/Berlin
      State: ENABLED
      Target:
        Arn: !GetAtt LambdaFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn
```

rain 1.7.5 artifact:

```yaml
  Schedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      GroupName: !Ref ScheduleGroupName
      ScheduleExpression: rate(5 minutes)
      ScheduleExpressionTimezone: Europe/Berlin
      FlexibleTimeWindow:
        Mode: "OFF"
      State: ENABLED
      Target:
        Arn: !GetAtt LambdaFunction.Arn
        RoleArn: !GetAtt ScheduleRole.Arn
```

The Documentation is also unclear what exacly they want for values: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-scheduler-schedule-flexibletimewindow.html

```plaintext
Mode
Determines whether the schedule is invoked within a flexible time window. You must use quotation marks when you specify this value in your JSON or YAML template.

Allowed Values: "OFF" | "FLEXIBLE"

Required: Yes

Type: String

Allowed values: OFF | FLEXIBLE

Update requires: No interruption
```
