### ISSUE TITLE
tree command misses some resource dependencies

### ISSUE THREAD

**Issue by dhx-mike-palandra** [aws-cloudformation/rain#320]
```
$ rain --version
Rain v1.8.1 linux/amd64
```

Consider the following template:

```yaml
Parameters:
  BackupPlanId:
    Type: String

Resources:
  BackupSelection:
    Type: AWS::Backup::BackupSelection
    Properties:
      BackupPlanId: !Ref BackupPlanId
      BackupSelection:
        IamRoleArn: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/service-role/AWSBackupDefaultServiceRole
        Resources:
          - !Sub arn:${AWS::Partition}:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:file-system/${EfsFileSystem}
        SelectionName: !Sub ${AWS::StackName}

  EfsFileSystem:
    Type: AWS::EFS::FileSystem
```

`rain tree` outputs the following:
```yaml
Resources:
  BackupSelection:
    DependsOn:
      Parameters:
        - AWS::Partition
        - AWS::StackName
        - BackupPlanId
```

Notice that the following dependencies are missing:
  1. Parameter `AWS::AccountId` (referenced in `Resources.BackupSelection.Properties.BackupSelection.IamRoleArn`)
  2. Resource `EfsFileSystem` (referenced in property `Resources.BackupSelection.Properties.BackupSelection.Resources[0]`)
  
If `Resources.BackupSelection.Properties.BackupSelection.Resources[0]` is changed to `!Sub ${EfsFileSystem.Arn}`, the resource dependency is found:

```yaml
Resources:
  BackupSelection:
    DependsOn:
      Parameters:
        - AWS::Partition
        - AWS::StackName
        - BackupPlanId
      Resources:
        - EfsFileSystem
```
