### ISSUE TITLE
"Template has unresolved dependency" reported in error

### ISSUE THREAD

**Issue by mdaniel** [aws-cloudformation/rain#35]
Using the [two arg `Fn::Sub` flavor](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#YAML) seems to make rain angry

Given _(a fully-formed but simplistic)_:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Rain Sub Bug
Resources:
  NatEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Something
          Value:
            Fn::Sub:
            - |
              ${Alpha}
              # this is some more text
            - Alpha: "hello"
```
Emits:

```console
$ rain fmt -j unresolved_dep.bug.yml
Template has unresolved dependency 'hello' at Resources: NatEIP

$ rain fmt --debug --json unresolved_dep.bug.yml

panic: Template has unresolved dependency 'hello' at Resources: NatEIP [recovered]

goroutine 1 [running]:
github.com/aws-cloudformation/rain/cmd.Execute.func1()
panic(0x10718a0, 0xc00018a3a0)
github.com/aws-cloudformation/rain/cfn.Template.Graph(0xc00074c240, 0x10dee60, 0xc00074c240, 0x1, 0x203000)
github.com/aws-cloudformation/rain/cfn/format.(*encoder).sortKeys(0xc00023f910, 0x258d4e0, 0x7f98cb6ba108, 0x0)
github.com/aws-cloudformation/rain/cfn/format.encoder.formatMap(0x1, 0x0, 0x0, 0x1deeec0, 0xc00012f4a0, 0xc00018a240, 0x1, 0x1, 0x1deeec0, 0xc00012f500, ...)
github.com/aws-cloudformation/rain/cfn/format.encoder.format(0x1, 0x0, 0x0, 0x1deeec0, 0xc00012f4a0, 0xc00018a240, 0x1, 0x1, 0x1deeec0, 0xc00012f500, ...)
github.com/aws-cloudformation/rain/cfn/format.encoder.formatMap(0x1, 0x0, 0x0, 0x1deeec0, 0xc00012f4a0, 0xc00018a240, 0x1, 0x1, 0x1deeec0, 0xc00012f500, ...)
github.com/aws-cloudformation/rain/cfn/format.encoder.format(0x1, 0x0, 0x0, 0x1deeec0, 0xc00012f4a0, 0x25bd8a8, 0x0, 0x0, 0x1deeec0, 0xc00012f4a0, ...)
github.com/aws-cloudformation/rain/cfn/format.Template(0xc00070b8f0, 0x1, 0xc00070b800, 0x0, 0x0, 0x0)
github.com/aws-cloudformation/rain/cmd.glob..func4(0x2584d60, 0xc00070b7a0, 0x1, 0x3)
github.com/spf13/cobra.(*Command).execute(0x2584d60, 0xc00070b770, 0x3, 0x3, 0x2584d60, 0xc00070b770)
github.com/spf13/cobra.(*Command).ExecuteC(0x2585a80, 0xc00023ff78, 0x4061c5, 0xc000114058)
github.com/spf13/cobra.(*Command).Execute(...)
github.com/aws-cloudformation/rain/cmd.Execute(0x2585a80)
main.main()
```
but I confirmed that the stack does deploy successfully, and the `Sub` resolves as expected, and `cfn-lint` gives an a-ok. Running `rain check` also says `ok`, but `rain tree` similarly panics

_I tried it with current `master` (b9510ec6), v0.10.0, and also the `improve-parser` branch (2ac836ea), with the same result_
