### ISSUE TITLE
Missing Unsorted Flag For Package Command

### ISSUE THREAD

**Issue by null93** [aws-cloudformation/rain#362]
It seems like the `pkg` command is missing the `--unsorted` flag. Here is an example of what I mean. Consider `test.yaml` to have this content:

```yaml
Metadata:
  Foo: 1
  Bar: 2
```

When running `rain pkg test.yaml` it transforms it to this:

```yaml
Metadata:
  Bar: 2

  Foo: 1
```

Ideally there would be an option to not sort object keys (similar to the `fmt` command).

My particular use case is that I store metadata in templates where the position of the keys really matter.

I took a quick look at the source code and couldn't pin point exactly where this would be specified. I can try to submit a PR for this with a little guidance.
