### ISSUE TITLE
String type characters are converted to Boolean type characters

### ISSUE THREAD

**Issue by yu40ta** [aws-cloudformation/rain#480]
I am experiencing a phenomenon where source code that is recognized as "String" when deployed in the CloudFormation console is mistakenly converted to "Boolean" when deployed by rain.

For example, the following source code.

```yaml
  EC2StopSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: ec2-auto-stop
      Description: "Scheduler to auto stop EC2 instances"
      ScheduleExpression: "cron(0 19 * * ? *)"
      ScheduleExpressionTimezone: Asia/Tokyo
      FlexibleTimeWindow:
        Mode: "OFF" # this
      State: ENABLED
```

Below I paste a capture of the execution result in console and in rain.

## console
![image](https://github.com/user-attachments/assets/564a987c-cd6d-4a19-8947-17eccfd7c8fc)

## rain
![image](https://github.com/user-attachments/assets/49b5453b-590a-403e-bca2-5f1d37b84875)

Is this the expected behavior?
It appears that the double quotes have been removed for other properties except the FlexibleTimeWindow property too. (ex: Description property)
Unless this problem is resolved, templates that specify parameters with strings that can be Boolean will not be deployable.
