### ISSUE TITLE
`rain merge` removes quotation marks from YAML templates, resulting in `cfn-lint` errors

### ISSUE THREAD

**Issue by jhg023** [aws-cloudformation/rain#501]
When using the `rain merge` command, I noticed that quotation marks are stripped from YAML templates. This behavior is problematic when dealing with CFN templates that require certain values to be enclosed in quotation marks. Specifically, I encountered this issue while defining an EventBridge schedule:

**Original template:**
```yaml
MyEventBridgeSchedule:
  Type: AWS::Scheduler::Schedule
  Properties:
    FlexibleTimeWindow:
      Mode: "OFF"
```

**Merged YAML after using `rain merge`:**
```yaml
MyEventBridgeSchedule:
  Type: AWS::Scheduler::Schedule
  Properties:
    FlexibleTimeWindow:
      Mode: OFF
```

According to the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-scheduler-schedule-flexibletimewindow.html), the `Mode` property must be enclosed in quotation marks (e.g., `"OFF"` or `"FLEXIBLE"`). The removal of these quotation marks by `rain merge` leads to a validation error when using `cfn-lint`:

```
E3030 False is not one of ['OFF', 'FLEXIBLE']
template.yml:1417:9
```

**Workaround:**
I am currently working around this issue by manually readding the quotation marks using Linux's `sed` command after running `rain merge`:
```sh
sed -i 's/Mode: OFF/Mode: "OFF"/' template.yml
```

**Feature request:**
I was told in Discord that the `fmt` command already supports this via a parameter, but it would be useful if `merge` could support the same behavior.

Thanks so much!
