### ISSUE TITLE
build command produces incorrect output for resource type AWS::ECR::ReplicationConfiguration but only in non-bare mode

### ISSUE THREAD

**Issue by dhx-mike-palandra** [aws-cloudformation/rain#523]
```
$ rain --version
Rain v1.15.0 linux/amd64
```

AFAICT, bare output is correct:
```
$ rain build --bare AWS::ECR::ReplicationConfiguration
AWSTemplateFormatVersion: 2010-09-09

Description: Generated by rain

Resources:
  ReplicationConfiguration:
    Type: AWS::ECR::ReplicationConfiguration
    Properties:
      ReplicationConfiguration:
        Rules:
          - Destinations:
              - Region: '[0-9a-z-]{2,25}'
                RegistryId: ^[0-9]{12}$
              - Region: '[0-9a-z-]{2,25}'
                RegistryId: ^[0-9]{12}$
          - Destinations:
              - Region: '[0-9a-z-]{2,25}'
                RegistryId: ^[0-9]{12}$
              - Region: '[0-9a-z-]{2,25}'
                RegistryId: ^[0-9]{12}$
```

Non-bare output is incorrect.  In particular, notice that the required `RegistryId` key is missing:
```
AWSTemplateFormatVersion: 2010-09-09

Description: Generated by rain

Resources:
  ReplicationConfiguration:
    Type: AWS::ECR::ReplicationConfiguration
    Properties:
      ReplicationConfiguration:
        Rules:
          - RepositoryFilters:
              - Filter: ^(?:[a-z0-9]+(?:[._-][a-z0-9]*)*/)*[a-z0-9]*(?:[._-][a-z0-9]*)*$
                FilterType: PREFIX_MATCH
              - Filter: ^(?:[a-z0-9]+(?:[._-][a-z0-9]*)*/)*[a-z0-9]*(?:[._-][a-z0-9]*)*$
                FilterType: PREFIX_MATCH
            Destinations:
              - Region: '[0-9a-z-]{2,25}'
              - Region: '[0-9a-z-]{2,25}'
          - RepositoryFilters:
              - Filter: ^(?:[a-z0-9]+(?:[._-][a-z0-9]*)*/)*[a-z0-9]*(?:[._-][a-z0-9]*)*$
                FilterType: PREFIX_MATCH
              - Filter: ^(?:[a-z0-9]+(?:[._-][a-z0-9]*)*/)*[a-z0-9]*(?:[._-][a-z0-9]*)*$
                FilterType: PREFIX_MATCH
            Destinations:
              - Region: '[0-9a-z-]{2,25}'
              - Region: '[0-9a-z-]{2,25}'
```
