### ISSUE TITLE
Adding `accounts` to the configuration file is not reflected when second time deploying a stack set

### ISSUE THREAD

**Issue by kaito3desuyo** [aws-cloudformation/rain#586]
I'm trying to deploy a StackSet.
Once deployed, adding `accounts` to the configuration file does not actually deploy the stack instance.

```yaml:config.yaml
StackSet:
  capabilities:
    - CAPABILITY_NAMED_IAM
    - CAPABILITY_AUTO_EXPAND

StackSetInstances:
  accounts:
    - "123456789000"
    - "123456789001" <-- added but no deployed
  regions:
    - ap-northeast-1
```

```
$ rain stackset deploy example.stackset.yaml ExampleCFnStackSet --config config.yaml
Stack set already exists. Do you want to update it? (Y/n)
Updating stack set instances in...
accounts: [123456789000]
regions: [ap-northeast-1]
Submitted UPDATE stack set operation with ID: bb2165d5-e818-4b3d-8ed4-086680b7d2a2
Stack set operation resulted with state: SUCCEEDED
Stack set update has been completed.
There are no new instances to be created.
```
