### ISSUE TITLE
When outputting to JSON, `!Contains` (`"Fn::Contains") is removed erroneously.

### ISSUE THREAD

**Issue by JoseRolles** [aws-cloudformation/rain#612]
To reproduce, create the following file.

template.yaml
```yaml
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert: !Not
          - !Contains
            - - '1'
              - '2'
              - '3'
              - '4'
              - '5'
            - !Ref BootstrapVersion
```

Then run the following command.

```bash
$ rain fmt --unsorted --json template.yaml
{
    "Rules": {
        "CheckBootstrapVersion": {
            "Assertions": [
                {
                    "Assert": {
                        "Fn::Not": [
                            [
                                [
                                    "1",
                                    "2",
                                    "3",
                                    "4",
                                    "5"
                                ],
                                {
                                    "Ref": "BootstrapVersion"
                                }
                            ]
                        ]
                    }
                }
            ]
        }
    }
}
```

The output should be the following instead.
```json
{
    "Rules": {
        "CheckBootstrapVersion": {
            "Assertions": [
                {
                    "Assert": {
                        "Fn::Not": [
                            {
                                "Fn::Contains": [
                                    [
                                        "1",
                                        "2",
                                        "3",
                                        "4",
                                        "5"
                                    ],
                                    {
                                        "Ref": "BootstrapVersion"
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```

**Comment by JoseRolles** [comment]
Hmmm, apparently the short form doesn't work, but the full function name works.

```yaml
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert: !Not
          - "Fn::Contains":
            - - '1'
              - '2'
              - '3'
              - '4'
              - '5'
            - !Ref BootstrapVersion
```
