### ISSUE TITLE
Rain 1.2 regression: ContentUri does not work with content in a subfolder

### ISSUE THREAD

**Issue by Jumziey** [aws-cloudformation/rain#64]
Template: 
```
AWSTemplateFormatVersion: "2010-09-09"

Description: Example layer

Transform: AWS::Serverless-2016-10-31

Resources:
  Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: LayerExample
      Description: An example layer
      ContentUri: content-folder/content.zip
      RetentionPolicy: Retain
```
under `content-folder/` put a zip of just about anything (for instance a file.txt with hello-world). Then deploy the layer.

With rain 1.1.2 it deploys fine. With rain 1.2 you get the error: `error creating changeset: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [AudioWaveformExtractorLayer12ea7a4976] is invalid. 'ContentUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.`

Have only tried with this with the `AWS::Serverless::LayerVersion` resource. It's a bit complicated by Transform, but it's consistent in the same docker image, only differing in rain version. 

Keep up the great work! This tool really makes my days way more fun.
