### ISSUE TITLE
Feature Request: Allow Ignoring Specific Lines or Blocks in Formatting

### ISSUE THREAD

**Issue by leinardi** [aws-cloudformation/rain#655]
### Description

It would be helpful if `rain fmt` supported a way to ignore specific lines or blocks in a CloudFormation template. This is useful when formatting needs to be skipped for certain parts of the file due to external constraints (e.g., manually controlled formatting).

### Proposed Solutions

Many linters support this through inline comments. For example:

- **Ignoring a single line**:
  ```yaml
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket  # rain disable-line
  ```

- **Ignoring a block**:
  ```yaml
  # rain disable
  Resources:
    MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: MyCustomBucket
  # rain enable
  ```

- **Ignoring an entire file**:
  ```yaml
  # rain disable-file
  ```

This behavior is similar to tools like `yamllint`, which use structured comments to temporarily disable specific checks.

### Benefit

- Enables finer control over formatting.
- Helps preserve intentional formatting decisions.
- Avoids the need for workarounds like separating specific parts into external files.
