### ISSUE TITLE
S3 Directives Override package Bucket/BucketOwner

### ISSUE THREAD

**Issue by georgealton** [aws-cloudformation/rain#656]
When rain packages a templates all objects are uploaded to the S3 Bucket passed into the pkg command, but sometimes artifacts need to be in specific Buckets.

My use case here:
In a CloudFormation Stack, I define an AWS::CloudFormation::StackSet Resource, and that StackSet deploys to different Regions. I'd like that template to look something like

```yaml
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  Hooks:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: Hooks
      StackInstancesGroup:
        - Regions:
            - us-east-1
          DeploymentTargets:
            OrganizationalUnitIds:
              - ou-xyz-123
          ParameterOverrides:
            - ParameterKey: S3URIAWSDynamoDBTable
              ParameterValue: !Rain S3
                Path: path/to/ddb/hook.guard
                Bucket: hooks-us-east-1
                BucketOwner: 012345678912
                Extension: guard
        - Regions:
            - eu-west-1
          DeploymentTargets:
            OrganizationalUnitIds:
              - ou-xyz-123
            - ParameterKey: S3URIAWSDynamoDBTable
              ParameterValue: !Rain S3
                Path: path/to/ddb/hook.guard
                Bucket: hooks-eu-west-1
                BucketOwner: 012345678912
                Extension: guard
         ...
```

The template the stackset deploys takes the S3 URI (generated by rain) as a Parameter.

```yaml
Parameters:
  S3URIAWSDynamoDBTable:
    Type: String

Resources:
  AWSDynamoDBTable:
    Type: AWS::CloudFormation::GuardHook
    Properties:
      Alias: Some::AWSDynamoDBTable::Policy
      ExecutionRole: !Sub arn:aws:iam::${AWS::AccountId}:role/CloudFormationHooks
      FailureMode: WARN
      HookStatus: ENABLED
      LogBucket: !Sub some-aws-cloudformation-hooks-logs-${AWS::Region}
      RuleLocation:
        Uri: !Ref S3URIAWSDynamoDBTable
      TargetFilters:
        InvocationPoints:
          - PRE_PROVISION
        Actions:
          - CREATE
          - UPDATE
        TargetNames:
          - AWS::DynamoDB::Table
      TargetOperations:
        - RESOURCE
        - CHANGE_SET
```

Would you be open to this as a feature?

I solve this currently by doing the artifact uploads in CI outside of rain, then passing the Object Names in as Parameters to the StackSet, and building the S3 URIs with !Sub, but I'd like to do this in `rain` as it reduces the wiring complexity.
