### ISSUE TITLE
Update .pre-commit-hooks.yaml to use rain instead of cfn-format

### ISSUE THREAD

**Issue by leinardi** [aws-cloudformation/rain#671]
Hi Rain team 👋

I noticed that the current `.pre-commit-hooks.yaml` in the repository is [[quite outdated](https://github.com/aws-cloudformation/rain/blob/main/.pre-commit-hooks.yaml)](https://github.com/aws-cloudformation/rain/blob/main/.pre-commit-hooks.yaml). It references an old tool called `cfn-format`, which hasn’t been maintained and is not part of the Rain CLI:

```yaml
- id: cfn-format
  name: Format CloudFormation templates
  entry: cfn-format -w
  language: golang
  files: \.template$
  description: Format CloudFormation templates
```

Since Rain now provides a robust `fmt` command, it would be great to update the pre-commit hook definition to use Rain directly.

Additionally, having **two separate hooks** would be very helpful:
1. One that **formats** templates using `rain fmt -w`
2. One that **verifies formatting** without modifying files using `rain fmt -v`

This would align with best practices in the [[pre-commit framework](https://pre-commit.com/)](https://pre-commit.com/) by allowing developers to:
- Run formatting automatically before each commit (`-w`)
- Enforce formatting rules in CI pipelines without modifying files (`-v`)

An example of what the updated hooks could look like:

```yaml
- id: rain-format
  name: rain format
  description: Format AWS CloudFormation templates
  entry: rain
  language: golang
  files: \.(yml|yaml|json)$
  args: ["fmt", "-w"]

- id: rain-verify
  name: rain verify
  description: Verify AWS CloudFormation templates formatting without modifying files
  entry: rain
  language: golang
  files: \.(yml|yaml|json)$
  args: ["fmt", "-v"]
```

I'll create a PR to fix this issue.
